version: "3.7"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: docker-app-go
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/app
    environment:
      PORT: "8080"