version: "3.7"

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # volume for data storage
      - postgres-data:/var/lib/postgresql/data
      # volume with db initial scripts when db doesn't exist yet
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data: